CREATE TABLE products (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  user_id int NOT NULL,
  name varchar(60) NOT NULL,
  price float NOT NULL DEFAULT 0,
  image_url varchar(255) NOT NULL,
  stock int NOT NULL DEFAULT 0,
  condition varchar(6) NOT NULL,
  is_purchaseable boolean NOT NULL DEFAULT true,
  created_at timestamp NOT NULL,
  updated_at timestamp NOT NULL,
  PRIMARY KEY(id),
  CONSTRAINT fk_user 
    FOREIGN KEY(user_id) 
    REFERENCES users(id)
	  ON DELETE SET NULL
);

CREATE TABLE tags (
  product_id int NOT NULL,
  name varchar(255) NOT NULL,
  created_at timestamp NOT NULL,
  updated_at timestamp NOT NULL,
  CONSTRAINT fk_product
    FOREIGN KEY(product_id) 
	  REFERENCES products(id)
	  ON DELETE SET NULL
);