CREATE TABLE bank_accounts (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  user_id int NOT NULL,
  bank_name varchar(15) NOT NULL,
  bank_account_name varchar(15) NOT NULL,
  bank_account_number varchar(15) NOT NULL,
  created_at timestamp NOT NULL,
  updated_at timestamp NOT NULL,
  PRIMARY KEY(id),
  CONSTRAINT fk_user 
    FOREIGN KEY(user_id) 
    REFERENCES users(id)
	  ON DELETE SET NULL
);